# Generated by Django 2.2.3 on 2019-07-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='name',
        ),
        migrations.AddField(
            model_name='day',
            name='number',
            field=models.IntegerField(default=1, help_text='Enter the number of the day here.'),
            preserve_default=False,
        ),
    ]
