# Generated by Django 2.2.3 on 2019-07-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190711_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='description',
            field=models.TextField(default=1, help_text='Enter the decription of the day here'),
            preserve_default=False,
        ),
    ]
