# Generated by Django 2.2.3 on 2019-07-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_day_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='description',
            field=models.TextField(blank=True, help_text='Enter the description of the day here', null=True),
        ),
    ]
