# Generated by Django 2.2.3 on 2019-07-12 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190711_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendaitem',
            name='description',
            field=models.TextField(help_text='Enter the description of the agenda item here.'),
        ),
        migrations.AlterField(
            model_name='day',
            name='description',
            field=models.TextField(blank=True, help_text='Enter the description of the day here.', null=True),
        ),
        migrations.CreateModel(
            name='GuestLecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(help_text='Enter the time when the guest lecture here will end.')),
                ('end_time', models.TimeField(help_text='Enter the time when the guest lecture here will start.')),
                ('description', models.TextField(help_text='Enter the description of guest lecture here.')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Day')),
            ],
        ),
    ]
