# Generated by Django 2.2.3 on 2019-07-12 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190712_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestlecture',
            name='speaker',
            field=models.CharField(default=1, help_text='Enter the name of the guest speaker here.', max_length=300),
            preserve_default=False,
        ),
    ]
